#.github/workflows/integration-workflow.yml
name: Deploy to TrailHead Env
on:
  pull_request:
    branches:
      - Master
  #schedule:
    # every days at 2AM
  #  - cron:  '0 2 * * *'
  #pull_request:
  #  branches:
  #    - sit

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DLP-CAP
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      # Store secret for dev hub
      - name: 'Populate auth file with SITORG_SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.SITORG_SFDX_URL}} > ./SITORG_SFDX_URL.txt'

      # Authenticate CI ORG
      - name: 'Authenticate INTEGRATION ORG'
        run: sfdx force:auth:sfdxurl:store -f ./SITORG_SFDX_URL.txt -a sitorg -d

      #Debug create scratch org: ls folder
      - name: List the files in the folder
        run: ls -l

      # Push source 
      - name: Deploy source
        run: sfdx force:source:deploy --sourcepath force-app/main -u sitorg -l RunLocalTests -w 30 --json --loglevel fatal
